### ISSUE TITLE
[feature]新增webui工具管理及配置平台

### ISSUE THREAD

**Issue by ruizeng** [PandoCloud/pando-cloud#13]
### 背景

* 目前平台通过pdcfg小工具进行基本的信息配置，不太方便且学习门槛较高
* 平台目前都是通过系统工具和脚本对系统进行监控，使用门槛高且不直观

需要开发一个基于web的管理平台，除了上述功能，后续陆续加入统计、日志分析、数据分析等常用功能。

### 需求
webui分为首页、配置、监控、统计、日志、分析等子模块:

* 首页：展示系统关键信息，如当前激活设备数，在线设备数，系统运行情况。
* 配置：主要通过registry对平台进行配置，如配置产品等。
* 监控：监控当前系统运行状态，及各个服务的状态，以及当前的负载情况。
* 统计：统计报表如总设备数，设备数增长趋势等。
* 日志：查看和搜索日志
* 分析：后续会对接数据平台，读设备的数据进行分析挖掘等。
* 帮助：使用说明、版本说明、项目介绍等。

### 技术方案

* web框架：beego
* 前端：bootstrap+jquery

### 参考原型
[pando-webui.zip](https://github.com/PandoCloud/pando-cloud/files/72405/pando-webui.zip)

### 页面模板
[AdminLTE-2.3.0.zip](https://github.com/PandoCloud/pando-cloud/files/72921/AdminLTE-2.3.0.zip)

**Comment by wangbiaobiao** [comment]
昨天看的模版也放在附件中吧
