### ISSUE TITLE
apiprovider服务启动出错

### ISSUE THREAD

**Issue by jatywm** [PandoCloud/pando-cloud#23]
`$GOPATH/bin/apiprovider -etcd http://localhost:2379 -rpchost localhost:20031 -httphost 120.25.212.111:8443 -loglevel debug -usehttps -keyfile /iotcloud/pandocloud/privkey.pem -cafile /iotcloud/pandocloud/cacert.pem &
[1] 1537
root@iZ94m8aipu7Z:~# {"ip":"10.116.119.223","level":"info","msg":"server apiprovidor init success.","service":"apiprovidor","time":"2016-02-24T10:35:16+08:00"}
{"ip":"10.116.119.223","level":"error","msg":"dial tcp 127.0.0.1:5672: getsockopt: connection refused","service":"apiprovidor","time":"2016-02-24T10:35:16+08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x405ac3]

goroutine 21 [running]:
main.(*Notifier).updateApplications(0x0, 0x0, 0x0)
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:66 +0x213
created by main.(*Notifier).Run
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:153 +0x45

goroutine 1 [runnable]:
bytes.makeSlice(0xba, 0x0, 0xdb6db6db6db6db, 0xe)
        /usr/local/go/src/bytes/buffer.go:188
bytes.(*Buffer).grow(0xc820148160, 0x3a, 0x4)
        /usr/local/go/src/bytes/buffer.go:103 +0x282
bytes.(*Buffer).WriteString(0xc820148160, 0xc8200eb880, 0x3a, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:140 +0x4b
encoding/json.(*encodeState).string(0xc820148160, 0xc8200eb880, 0x3a, 0xc8200eb880, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:852 +0x14e
encoding/json.stringEncoder(0xc820148160, 0x96f5c0, 0xc8200e7400, 0x58, 0x0)
        /usr/local/go/src/encoding/json/encode.go:546 +0x2c4
encoding/json.(*encodeState).reflectValue(0xc820148160, 0x96f5c0, 0xc8200e7400, 0x58)
        /usr/local/go/src/encoding/json/encode.go:297 +0x6b
encoding/json.interfaceEncoder(0xc820148160, 0x962a00, 0xc8200e7490, 0x54, 0xc8200e7400)
        /usr/local/go/src/encoding/json/encode.go:555 +0xd8
encoding/json.(*mapEncoder).encode(0xc8200e8070, 0xc820148160, 0xa1aca0, 0xc8200e3a10, 0x15, 0x0)
        /usr/local/go/src/encoding/json/encode.go:617 +0x344
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc820148160, 0xa1aca0, 0xc8200e3a10, 0x15, 0xc8200e3a00)
        /usr/local/go/src/encoding/json/encode.go:627 +0x51
encoding/json.(*encodeState).reflectValue(0xc820148160, 0xa1aca0, 0xc8200e3a10, 0x15)
        /usr/local/go/src/encoding/json/encode.go:297 +0x6b
encoding/json.(*encodeState).marshal(0xc820148160, 0xa1aca0, 0xc8200e3a10, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:270 +0xa9
encoding/json.Marshal(0xa1aca0, 0xc8200e3a10, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:135 +0x83
github.com/Sirupsen/logrus.(*JSONFormatter).Format(0xc8200e67f0, 0xc8200eb8c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/golang/src/github.com/Sirupsen/logrus/json_formatter.go:36 +0x864
github.com/Sirupsen/logrus.(*Entry).Reader(0xc8200eb8c0, 0xc808359204, 0x0, 0x0)
        /root/golang/src/github.com/Sirupsen/logrus/entry.go:44 +0x67
github.com/Sirupsen/logrus.Entry.log(0xc82001b3c0, 0xc8200e2d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x414404, 0xc8200eb880, ...)
        /root/golang/src/github.com/Sirupsen/logrus/entry.go:94 +0x282
github.com/Sirupsen/logrus.(*Entry).Info(0xc8200ea940, 0xc8200f3c40, 0x1, 0x1)
        /root/golang/src/github.com/Sirupsen/logrus/entry.go:129 +0x8c
github.com/Sirupsen/logrus.(*Entry).Infof(0xc8200ea940, 0xc78de0, 0x27, 0xc8200f3d00, 0x2, 0x2)
        /root/golang/src/github.com/Sirupsen/logrus/entry.go:173 +0x139
github.com/PandoCloud/pando-cloud/pkg/server.(*HTTPServer).Start(0xc8200e3320, 0x0, 0x0)
        /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/http_server.go:30 +0x422
github.com/PandoCloud/pando-cloud/pkg/server.Run(0x0, 0x0)
        /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/server.go:215 +0x235
main.main()
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/main.go:37 +0x3f8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 22 [runnable]:
main.(*Notifier).processEvents(0x0, 0xc8200eb7c0, 0x37)
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:138
created by main.(*Notifier).Run
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:154 +0x67

goroutine 23 [runnable]:
main.(*Notifier).processStatus(0x0, 0xc8200eb7c0, 0x37)
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:59
created by main.(*Notifier).Run
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:155 +0x89
`

已经修复！
问题：没有安装RabbitMQ，
解决：sudo apt-get install rabbitmq-server-y

**Comment by ruizeng** [comment]
好的，是没有安装rabbitmq的原因，参考最新文档安装。
