### ISSUE TITLE
run.sh error  panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gmshiot** [PandoCloud/pando-cloud#24]
Hello!
     **When I setup pandocloud on ubuntu14.04,some errors occurred.the following error:**
root@pando:~/golang# cd bin
root@pando:~/golang/bin# ls
apiprovider  controller  devicemanager  httpaccess  mqttaccess  registry
root@pando:~/golang/bin# cd $GOPATH/src/github.com/PandoCloud/pando-cloud
root@pando:~/golang/src/github.com/PandoCloud/pando-cloud# ls
build       docs    LICENSE       pkg        services  tools
Dockerfile  Godeps  make_deps.sh  README.md  tests     unit_test.sh
root@pando:~/golang/src/github.com/PandoCloud/pando-cloud# sudo sh -x .ild/localnux/run.sh
+ killall -9 httpaccess registry apiprovider devicemanager controller mqttaccess
httpaccess: no process found
registry: no process found
apiprovider: no process found
devicemanager: no process found
controller: no process found
mqttaccess: no process found
+ exit 0
root@pando:~/golang/src/github.com/PandoCloud/pando-cloud# + + /bin/mqttaccess -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20030 -tcphost internal:1883 -usetls -keyfile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile/bin/controller /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
 -etcd.ild/localnux/run.sh: 11: .ild/localnux/run.sh:  http://localhost:2379+  -loglevel debug -rpchost localhost:20032/bin/mqttaccess: not found

.ild/localnux/run.sh: 10: .ild/localnux/run.sh: /bin/controller: not found
/bin/devicemanager -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20033
.ild/localnux/run.sh: 9: .ild/localnux/run.sh: /bin/devicemanager: not found
+ /bin/apiprovider -etcd http://localhost:2379 -loglevel debug -httphost :8888
.ild/localnux/run.sh: 8: .ild/localnux/run.sh: /bin/apiprovider: not found
+ /bin/registry -etcd http://localhost:2379 -rpchost localhost:20034 -aeskey ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP -dbhost localhost -dbname PandoCloud -dbport 3306 -dbuser root -loglevel debug
.ild/localnux/run.sh: 7: .ild/localnux/run.sh: /bin/registry: not found
+ /bintpaccess -etcd http://localhost:2379 -httphost internal:443 -loglevel debug -usehttps -keyfile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
.ild/localnux/run.sh: 6: .ild/localnux/run.sh: /bintpaccess: not found                         

**When I execute command each row in run.sh,four commands sucessed,but apiprovider and controller commands run error below**:

**$GOPATH/bin/apiprovider -etcd http://localhost:2379 -loglevel debug  -httphost :8888 **&
[1] 1537
root@pando:/home/pando# {"ip":"192.168.1.168","level":"info","msg":"server apiprovidor init success.","service":"apiprovidor","time":"2016-03-02T16:06:43+08:00"}
{"ip":"192.168.1.168","level":"error","msg":"dial tcp [::1]:5672: getsockopt: connection refused","service":"apiprovidor","time":"2016-03-02T16:06:43+08:00"}
{"ip":"192.168.1.168","level":"info","msg":"HTTP Server Listen on :8888, use https: false","service":"apiprovidor","time":"2016-03-02T16:06:43+08:00"}
{"ip":"192.168.1.168","level":"info","msg":"starting http server ... OK","service":"apiprovidor","time":"2016-03-02T16:06:43+08:00"}
{"ip":"192.168.1.168","level":"info","msg":"sever launch successfully!","service":"apiprovidor","time":"2016-03-02T16:06:43+08:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x405b8c]

goroutine 9 [running]:
panic(0xb2a1e0, 0xc82000e0e0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.(*Notifier).updateApplications(0x0, 0x0, 0x0)
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:67 +0x20c
created by main.(*Notifier).Run
        /root/golang/src/github.com/PandoCloud/pando-cloud/services/apiprovider/notifier.go:154 +0x45

[1]+  Exit 2  

------------------------------------
**$GOPATH/bin/controller -etcd http://localhost:2379 -loglevel debug  -rpchost localhost:20032 **&
[1] 1542
root@pando:/home/pando# {"ip":"192.168.1.168","level":"info","msg":"server controller init success.","service":"controller","time":"2016-03-02T16:07:38+08:00"}
{"ip":"192.168.1.168","level":"error","msg":"NewController Error: dial tcp [::1]:5672: getsockopt: connection refused","service":"controller","time":"2016-03-02T16:07:38+08:00"}
---------------------------------------
**net port info below**:
root@pando:/home/pando# netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      1326/etcd       
tcp        0      0 127.0.0.1:28017         0.0.0.0:*               LISTEN      859/mongod      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      848/sshd        
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      1326/etcd       
tcp        0      0 192.168.1.168:1883      0.0.0.0:*               LISTEN      1384/mqttaccess 
tcp        0      0 192.168.1.168:443       0.0.0.0:*               LISTEN      1354tpaccess 
tcp        0      0 127.0.0.1:20030         0.0.0.0:*               LISTEN      1384/mqttaccess 
tcp        0      0 127.0.0.1:20033         0.0.0.0:*               LISTEN      1372/devicemanager
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      1326/etcd       
tcp        0      0 127.0.0.1:20034         0.0.0.0:*               LISTEN      1364/registry   
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      859/mongod      
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1001/mysqld     
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      1326/etcd       
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      885/redis-server 12
tcp6       0      0 :::8080                 :::*                    LISTEN      1024/java       
tcp6       0      0 :::22                   :::*                    LISTEN      848/sshd        
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      1024/java       
udp        0      0 0.0.0.0:68              0.0.0.0:*                           667/dhclient    
udp        0      0 0.0.0.0:64283           0.0.0.0:*                           667/dhclient    
udp6       0      0 :::9553                 :::*                                667/dhclient

**Comment by ruizeng** [comment]
sorry, the doc is out date. 
service `apiprovidor` and `controller` rely on `rabbitmq`. you need to install `rabbitmq` first.

``` bash
sudo apt-get install rabbitmq-server-y
````

**Comment by gmshiot** [comment]
I have setup  rabbitmq,  mqttaccess  process is normal

**Comment by ruizeng** [comment]
mqttaccess does not rely on rabbitmq. we implement mqtt protocol in mqttaccess in Go.
Actually rabbitmq is used for internal message queue and the  5672 port is the default listening port of rabbitmq.

**Comment by gmshiot** [comment]
wget  http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server_3.6.0-1_all.deb
sudo dpkg -i rabbitmq-server_3.6.0-1_all.deb

**Comment by ruizeng** [comment]
make sure your rabbitmq-server is successfully installed and launched.

**Comment by gmshiot** [comment]
this is what I execute, How I do? need execute "sudo apt-get install rabbitmq-server -y"?

**Comment by ruizeng** [comment]
just try `sudo apt-get install rabbitmq-server -y`, it will start rabbit automatically after installation.

**Comment by gmshiot** [comment]
Password: 
root@pando:/home/pando# sudo apt-get install rabbitmq-server -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rabbitmq-server
0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
Need to get 3,909 kB of archives.
After this operation, 4,867 kB of additional disk space will be used.
Get:1 http://hk.archive.ubuntu.com/ubuntu/ trusty/main rabbitmq-server all 3.2.4-1 [3,909 kB]
Fetched 3,909 kB in 6s (640 kB/s)                                              
Selecting previously unselected package rabbitmq-server.
(Reading database ... 79291 files and directories currently installed.)
Preparing to unpack .../rabbitmq-server_3.2.4-1_all.deb ...
Unpacking rabbitmq-server (3.2.4-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
ureadahead will be reprofiled on next reboot
Setting up rabbitmq-server (3.2.4-1) ...
Adding group `rabbitmq' (GID 116) ...
Done.
Adding system user `rabbitmq' (UID 109) ...
Adding new user `rabbitmq' (UID 109) with group `rabbitmq' ...
Not creating home directory `/var/lib/rabbitmq'.
 * Starting message broker rabbitmq-server
   ...done.
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by gmshiot** [comment]
kill and execute ,ok,thank you!

**Comment by gmshiot** [comment]
when I execute run.sh, show many not fund,Why? must execute each row alone in run.sh

**Comment by gmshiot** [comment]
I propose to revise rabbitMQ part of  this article https://github.com/PandoCloud/pando-cloud/blob/master/docs/zh-cn/quick-start/ubuntu.md

**Comment by ruizeng** [comment]
document updated. thx for your suggestion.
