### ISSUE TITLE
use pdcfg execute vendor add occur error：no server for registry，but six services are normal！

### ISSUE THREAD

**Issue by gmshiot** [PandoCloud/pando-cloud#25]
use pdcfg execute vendor add occur error：no server for registry，but six services are normal！Why？

root@pando:~# ps aux | grep $GOPATH/bin
root      2065  0.0  0.2 120468 11736 ?        Sl   11:38   0:00 /root/golang/bin/httpaccess -etcd http://localhost:2379 -httphost internal:443 -loglevel debug -usehttps -keyfile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
root      2066  0.0  0.3 124516 13060 ?        Sl   11:38   0:00 /root/golang/bin/registry -etcd http://localhost:2379 -rpchost localhost:20034 -aeskey ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP -dbhost localhost -dbname PandoCloud -dbport 3306 -dbuser root -loglevel debug
root      2067  0.0  0.3  47332 12148 ?        Sl   11:38   0:00 /root/golang/bin/apiprovider -etcd http://localhost:2379 -loglevel debug -httphost :8888
root      2068  0.0  0.2  53344 10748 ?        Sl   11:38   0:00 /root/golang/bin/devicemanager -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20033
root      2069  0.0  0.3 121012 12944 ?        Sl   11:38   0:00 /root/golang/bin/controller -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20032
root      2070  0.0  0.2  46364 11096 ?        Sl   11:38   0:00 /root/golang/bin/mqttaccess -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20030 -tcphost internal:1883 -usetls -keyfile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
root      2385  0.0  0.0  11748  2172 pts/1    S+   11:55   0:00 grep --color=auto /root/golang/bin
root@pando:~# $GOPATH/bin/pdcfg -etcd http://localhost:2379
{"ip":"192.168.1.100","level":"info","msg":"server pdcfg init success.","service":"pdcfg","time":"2016-03-30T12:08:42+08:00"}
> vendor add
vendor name: testvendor
vendor description: testvendor desc
{"ip":"192.168.1.100","level":"error","msg":"no server for registry","service":"pdcfg","time":"2016-03-30T12:09:31+08:00"}
no server for registry

**Comment by ruizeng** [comment]
make sure you have started `etcd`.

**Comment by gmshiot** [comment]
etcd  is started
root@pando:~# ps -ef | grep etcd
root      2065     1  0 11:38 ?        00:00:00 /root/golang/bin/httpaccess -etcd http://localhost:2379 -httphost internal:443 -loglevel debug -usehttps -keyfile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
root      2066     1  0 11:38 ?        00:00:01 /root/golang/bin/registry -etcd http://localhost:2379 -rpchost localhost:20034 -aeskey ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP -dbhost localhost -dbname PandoCloud -dbport 3306 -dbuser root -loglevel debug
root      2067     1  0 11:38 ?        00:00:01 /root/golang/bin/apiprovider -etcd http://localhost:2379 -loglevel debug -httphost :8888
root      2068     1  0 11:38 ?        00:00:00 /root/golang/bin/devicemanager -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20033
root      2069     1  0 11:38 ?        00:00:04 /root/golang/bin/controller -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20032
root      2070     1  0 11:38 ?        00:00:00 /root/golang/bin/mqttaccess -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20030 -tcphost internal:1883 -usetls -keyfile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /root/golang/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
root      7113  7089  0 18:08 pts/1    00:00:00 grep --color=auto etcd
root@pando:~#

**Comment by gmshiot** [comment]
Oh,etcd is stop,I don't know why it stoped,just start it.

**Comment by gmshiot** [comment]
ok,thank you!
