### ISSUE TITLE
question

### ISSUE THREAD

**Issue by limzhfor** [PandoCloud/pando-cloud#30]
在执行$GOPATH/bin/controller -etcd http://localhost:2379 -loglevel debug  -rpchost localhost:20032 &
之后报错：
{"ip":"10.0.2.15","level":"info","msg":"server controller init success.","service":"controller","time":"2016-04-21T15:53:44+08:00"}
{"ip":"10.0.2.15","level":"error","msg":"NewController Error: no reachable servers","service":"controller","time":"2016-04-21T15:53:56+08:00"}
想请问哪里出错了呢？其他五个服务都能正常运行，就是controller无法启动。怀疑是端口被占用了，修改了20032为20038，也是不行。

**Comment by ruizeng** [comment]
检查下依赖服务是否正常启动，特别是rabbitmq和mongodb

**Comment by Zhang-Jia** [comment]
执行node app.js时提示
var conf = jsonconf.parse(f);
^

TypeError: jsonconf.parse is not a function
提示没有jsonconf.parse这个函数
请问这个问题是由于我的nodejs版本不对在造成的吗，我用的是6.1.0版本

**Comment by ruizeng** [comment]
这里不负责nodejs基础问题的解答，谢谢。请自己参考资料进行问题定位。
