### ISSUE TITLE
ubuntu部署问题

### ISSUE THREAD

**Issue by husucceed** [PandoCloud/pando-cloud#31]
我这边完全按照说明一步步部署，但到后面提示有问题，还请指导。
当执行到sudo sh -x ./build/local/linux/run.sh提示出错，前面都没问题，试了好几遍。错误如下
root@ubuntu:~/golang/src/github.com/PandoCloud/pando-cloud# sudo sh -x ./build/local/linux/run.sh
+ killall -9 httpaccess registry apiprovider devicemanager controller mqttaccess
httpaccess: no process found
registry: no process found
apiprovider: no process found
devicemanager: no process found
controller: no process found
mqttaccess: no process found
+ exit 0
root@ubuntu:~/golang/src/github.com/PandoCloud/pando-cloud# + /bin/mqttaccess -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20030 -tcphost+  internal:1883 -usetls -keyfile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
./build/local/linux/run.sh: 11: ./build/local/linux/run.sh: /bin/mqttaccess: not found
/bin/controller -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20032
./build/local/linux/run.sh: 10: ./build/local/linux/run.sh: /bin/controller: not found
+ /bin/devicemanager -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20033
./build/local/linux/run.sh: 9: ./build/local/linux/run.sh: /bin/devicemanager: not found
+ /bin/apiprovider -etcd http://localhost:2379 -loglevel debug -httphost :8888
./build/local/linux/run.sh: 8: ./build/local/linux/run.sh: /bin/apiprovider: not found
+ /bin/registry -etcd http://localhost:2379 -rpchost localhost:20034 -aeskey ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP -dbhost localhost -dbname PandoCloud -dbport 3306 -dbuser root -loglevel debug
./build/local/linux/run.sh: 7: ./build/local/linux/run.sh: /bin/registry: not found
+ /bin/httpaccess -etcd http://localhost:2379 -httphost internal:443 -loglevel debug -usehttps -keyfile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
./build/local/linux/run.sh: 6: ./build/local/linux/run.sh: /bin/httpaccess: not found
2016-05-11 23:03:16.201141 I | etcdserver: start to snapshot (applied: 10001, lastsnap: 0)
2016-05-11 23:03:16.219505 I | etcdserver: saved snapshot at index 10001
2016-05-11 23:03:16.222697 I | etcdserver: compacted raft log at 5001

root@ubuntu:~/golang/src/github.com/PandoCloud/pando-cloud# sudo sh -x ./build/local/linux/run.sh
+ killall -9 httpaccess registry apiprovider devicemanager controller mqttaccess
httpaccess: no process found
registry: no process found
apiprovider: no process found
devicemanager: no process found
controller: no process found
mqttaccess: no process found
+ exit 0
root@ubuntu:~/golang/src/github.com/PandoCloud/pando-cloud# + /bin/mqttaccess -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20030 -tcphost internal:1883 -usetls -keyfile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem+  -cafile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
./build/local/linux/run.sh: 11: ./build/local/linux/run.sh: /bin/mqttaccess: not found
/bin/controller -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20032
./build/local/linux/run.sh: 10: ./build/local/linux/run.sh: /bin/controller: not found
+ /bin/devicemanager -etcd http://localhost:2379 -loglevel debug -rpchost localhost:20033
./build/local/linux/run.sh: 9: ./build/local/linux/run.sh: /bin/devicemanager: not found
+ /bin/apiprovider -etcd http://localhost:2379 -loglevel debug -httphost :8888
./build/local/linux/run.sh: 8: ./build/local/linux/run.sh: /bin/apiprovider: not found
+ /bin/registry -etcd http://localhost:2379 -rpchost localhost:20034 -aeskey ABCDEFGHIJKLMNOPABCDEFGHIJKLMNOP -dbhost localhost -dbname PandoCloud -dbport 3306 -dbuser root -loglevel debug
./build/local/linux/run.sh: 7: ./build/local/linux/run.sh: /bin/registry: not found
+ /bin/httpaccess -etcd http://localhost:2379 -httphost internal:443 -loglevel debug -usehttps -keyfile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem
./build/local/linux/run.sh: 6: ./build/local/linux/run.sh: /bin/httpaccess: not found
然后我查了一下bin目录下的文件如下
root@ubuntu:~/golang/bin# ls
apiprovider  controller  devicemanager  httpaccess  mqttaccess  registry
还请指导，谢谢。

**Comment by ruizeng** [comment]
没有设置好Go的环境变量。请再仔细阅读文档设置环境变量部分，确保环境变量设置成功。
