### ISSUE TITLE
docker里启动mqttaccess httpaccess时设置-tcphost的问题

### ISSUE THREAD

**Issue by isiot** [PandoCloud/pando-cloud#32]
以下是私聊群主的问题， 他让发布到issue，惠顾大家

**问：**
群主你好，攀多云启动mqttaccess的时候，设置参数 -tcphost 外网IP:1883 时，就不能成功启动，如果把外网IP换成localhost，或者干脆不写，或者换成179.1.0.9（容器分配得到的私有ip地址），就可以启动，请问我这是什么地方错了呢，谢谢
我用的docker，其中179.1.0.9是mqttaccess容器的ip地址

**答：**
那肯定啊，你容器里面是看不到外网ip的
你好好看下docker

**问：**
容器里看不到外网ip，这样的话，以-tcphost外网ip:1883参数启动matt，就会出现错误导致不能启动是吗，也就是还需要在容器和宿主机之间做一次ip映射

**答：**
恩，建议不要用容器装，ip这块比较麻烦的

**问：**
我使用分配给容器自己的ip（179.1.0.9）可以启动容器，不设置ip也可以启动mqttaccess，在8266固件里把设备登录后获得的accss_addr改成我的外网（公网）ip加1883的形式，这样设备端反向是能连接到pandocloud的，我研究容器下安装花了好多精力了，你能不能指导下容器中如何映射到外网

**答：**
你说的方法就是办法了，当然这样需要改固件，如果不改固件的话，我mqttaccess是支持一个环境变量的，可以让固件拉取到的mqttaccess ip是真实ip，把这个环境变量设置成最后固件需要得到的真实地址就行了
EnvTCPProxy          = "TCP_PROXY_ADDR"
EnvHTTPProxy         = "HTTP_PROXY_ADDR"

**问：**
以上EnvTCPProxy   ="TCP_PROXY_ADDR"直接加在 docker run 里面启动mqtt吗

**答：**
docker run的时候有参数可以指定环境变量的，你查下
docker的文档有加环境变量的用法的
不是这样加的，是加   “TCP_PROXY_ADDR=真实ip:真实端口”

**Comment by ruizeng** [comment]
感谢分享
