### ISSUE TITLE
mqttaccess keyfile cafile问题

### ISSUE THREAD

**Issue by isiot** [PandoCloud/pando-cloud#33]
按照git上的说明，启动mqttaccess的时候，设置
 -usetls -keyfile /go/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem -cafile /go/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/cert.pem 
我用的是docker

问题1、这个/go/src/github.com/PandoCloud/pando-cloud/pkg/server/testdata/key.pem我在虚拟机上怎么也找不到
问题2、tisan提供的8266sdk里的rgb led demo里没有看见设置tls的选项
问题3、看见mqtt交互过程中8266串口输出的debug，mqttaccess容器输出 “the first byte is not like handshake”字样，然后就断开了mqtt连接

**Comment by isiot** [comment]
更正：
mqttaccess输出  “the first byte is not like a tls handshake”  字样

**Comment by ruizeng** [comment]
逐一回答：
1. 文档告诉你指定keyfile和cafile的路径，这两个pem文件应该是你自己生成的，你可以网上搜索下生成pe文件的方法，然后放到程序可以访问到的路径，这两个参数指定路径就好了。
2. demo默认是不开启tls的
3. 是因为tisan-demo没开启tls但是你启动的mqtt-access开启了tls，你可以吧-usetls这个参数去掉启动就可以了。
