### ISSUE TITLE
通过devicekey获取设备信息，返回404错误问题

### ISSUE THREAD

**Issue by Zhang-Jia** [PandoCloud/pando-cloud#35]
@ruizeng，曾哥，请给我看一下这个问题怎么解决，什么时候来西安请你吃饭。
用curl发送http请求，通过devicekey获取设备信息，返回404错误，但是curl发送设备注册请求返回却正常，具体见这里http://note.youdao.com/yws/public/redirect/share?id=6be681f79bad4afe7a8b9d1aa14154f6&type=false

**Comment by paperayo** [comment]
app修改了吗，app默认访问pandocloud公网，你得修改app让它连接到你的服务器吧。

**Comment by Zhang-Jia** [comment]
@paperayo 你是开发者之一吗？更新后的API没有公布吗，free-iot手机软件改成自己的服务器后还能用吗？

**Comment by paperayo** [comment]
@Zhang-Jia 不是。。  更新后的api可以在对应的pandocloud那个项目里看到，因为不更新挺久了，要改的话得改挺多东西吧。。。你慢慢改肯定最终会可以用
