### ISSUE TITLE
docker部署后，设备注册和登录可运行，但是应用api不通

### ISSUE THREAD

**Issue by isiot** [PandoCloud/pando-cloud#37]
docker部署后，设备注册和登录可运行，但是应用api不通

1、vendor add 可以添加，也会出现vendor id，但是在下一步添加product的时候，输入此处vendor add 获得的vendor id，product add成功得到的vendor id是0，而不是我输入的vendor id

2、按照 设备接入API 说明，完全可以实现设备注册和登录：
用的是 firefox下的restclient插件，虚拟机里添加了443端口映射，rest连接的时候，用的是  https://ip/v1/devices/registration的形式，然后在Body里面添加 json数据

3、按 应用服务器API接口  说明，却总是不成功，尝试了以下方法也不行：
进行了app add操作，获得了appkey，AppDomain设置的是 “*”
在虚拟机添加了  8888 端口映射
使用 firefox下的restclient插件
尝试了使用 
https://ip:8888/application/v1/device/info
http://ip:8888/application/v1/device/info
以及在启动apiprovider时将端口设置为80后使用http://ip/application/v1/device/info的形式
都不行，现象是，返回404 没有找到 错误

疑惑：：
在docker里使用 docker ps -a看见
controller和 apiprovider
处于停止运行状态

**Comment by isiot** [comment]
用如下命令启动controller时
docker run -it --name controller --link etcd --link mongo pandocloud/pando-cloud controller -etcd http://etcd:2379 -mongohost mongo -rpchost internal:20032 -loglevel debug

出现以下错误
{"ip":"172.17.0.11","level":"info","msg":"server controller init success.","service":"controller","time":"2016-08-06T15:08:02Z"}
{"ip":"172.17.0.11","level":"error","msg":"NewController Error: dial tcp [::1]:5672: getsockopt: connection refused","service":"controller","time":"2016-08-06T15:08:02Z"}

**Comment by ruizeng** [comment]
使用docker镜像进行部署需要对docker比较熟悉，不熟悉话的建议先多了解下。
