### ISSUE TITLE
cloud端更改设备名称后，freeIOT下拉刷新设备名称不会改变

### ISSUE THREAD

**Issue by zxc1021** [PandoCloud/pando-cloud#4]
cloud端更改设备名称后，freeIOT下拉刷新只会更新设备是否在线，而设备名称不会改变。 这应该也算是bug吧。应该是通信协议里面的问题，下拉刷新的时候返回设备名称就可以了。

**Comment by ruizeng** [comment]
请提供详细的环境，ios还是android客户端？什么手机？修改的时候是否显示成功？

**Comment by zxc1021** [comment]
android手机，小米3，刚刚又试了一下，云端改了手机不会同步，手机改了同样云端不会同步。 你们这个是不是本身就没做设备名称同步？ 手机跟云端各管各的？

**Comment by ruizeng** [comment]
你的意思添加过的设备，改过了名字。然后删除后重新添加，名字又是默认的名字而不是改过的名字是么？我们是这个逻辑，当然你可以根据自己的需要定制app

**Comment by zxc1021** [comment]
感觉你们这个逻辑有点乱， 我是这样操作的： 三色灯的demo测试通过后，在你们后台cloud上改了名字（比如三色灯->三色灯111）成功，此时freeiot并没有删除设备，下拉刷新时名称不更新（仍然是三色灯）。而此时我用freeiot来更改设备名称（三色灯->三色灯222）成功，此时用微信扫描添加时，设备名称为三色灯222。感觉你们三端名称应该保持一致，要不然会给用户造成困扰。（微信、云端、freeiot端）

**Comment by ruizeng** [comment]
你是如何在云端修改名称的？我们没有开放这种功能啊

**Comment by zxc1021** [comment]
tisan的工作区。

**Comment by ruizeng** [comment]
是这样的，tisan的工作区的名称是产品名称，而freeiot上你修改的是设备名称。
1. 同一个产品不同的用户手上的设备用户可以自己起名字，但是这个修改是不会反应到产品名的，因为产品名是开发者起的，是更通用的。
2. 同理，如果你作为开发者修改了产品名称，这个改变也是不会反应到用户的设备名称上的，否则你之前为了个人喜好而修改的名称又被该回去了，是不合理的。
3. 只有用户删除设备重新添加，设备名才会默认设置为产品名。

这是我们为了通用性而设计的逻辑，如果你的产品由自己的逻辑，可以参考我们的样例自己开发。

**Comment by zxc1021** [comment]
oh  是的，还是你们有经验，呵呵 赞一个

**Comment by ruizeng** [comment]
感谢你的反馈:P
