### ISSUE TITLE
无法接收到请求到手机app请求问题

### ISSUE THREAD

**Issue by linrx1511** [PandoCloud/pando-cloud#6]
我的温湿度的板子长时间放着，就会出现一直保持心跳连接(心跳包打印正常)，但用手机却查不到当前状态，但显示设备还是在线的，只是板子无法接收到请求。

**Comment by ruizeng** [comment]
请问你是自己部署的我们的pando后台么

**Comment by linrx1511** [comment]
不是，是用你们提供的服务器，都是你们提供的例程

**Comment by ruizeng** [comment]
可能是连接出错了。感谢反馈，我们正在定位
