### ISSUE TITLE
[feature]registry增加缓存

### ISSUE THREAD

**Issue by ruizeng** [PandoCloud/pando-cloud#9]
### 背景
`registry`服务对数据库中`vendor product application device`表进行管理。其他服务通过`registry`对这些表中的记录进行查询和修改等操作。目前都是通过直接操作数据库的方式进行操作，当请求量大的时候会出现性能问题，所以需要增加缓存。

### 业务场景
`vendor`,`product`,`application`三个表都是典型的*少写多读*场景。平台只有在用户需要对厂商、产品和应用的信息进行修改时，才会写db，其余都是通过id去读取（如校验key等）。并且这三个表的数据量都不会很大（甚至大部分情况只有个位数），所以可以直接进行**全量内存缓存**。

`device`表数据量比其余三个表大很多，但是读频率小很多，且基本没有静态热点。暂时不考虑进行缓存操作（后续考虑根据动态热点缓存并加入分片逻辑）。

### 实现方法
需先实现一个通用的基于内存的列表缓存库（放在pkg目录中以便复用和测试），并通过该库缓存全量`vendor`,`product`,`application`三个表数据。
1. 写入条目时时直接写db；
2. 读取时先读缓存，如果失败则读db并更新缓存，如果db也不存在则返回失败。

**Comment by g4zhuj** [comment]
1. models的结构体中，Vendor有Products数组，Product有Devices数组，这两个结构体中的数组有被用到吗？
２．对于这几个表内容的存储，我打算使用map，前几个表用id作为key，对于Device有用到三个key作为查询，分别为id,identifier,key，这里有两种方式，第一种，考虑到设备表不大每个key存储一份Device的值，每次更新或删除时三个key的副本都会操作．第二种，Device的值只存储一份，identifier，key这两个键的Value存储Device的id，查询时先找到id，再通过id找到对应的Device，而更新时只更新一个副本，删除时删除副本以及所有key．这里有什么意见和建议吗？

以上

**Comment by ruizeng** [comment]
1. 这个只是orm用来读取关联数据的，目前没有太多用处
2. 前三个表用map是没有任何问题的，id做key
3. device操作要复杂很多，而且数据量大，可能要根据当前读取的热点做LRU缓存。具体的数据结构我认为第二种更合理。其实device表的读取不会通过key去读，这里是我之前写的时候的一个问题，我会马上修改过来。只需要考虑通过id和通过identifier去读取的情况。而实际的业务场景，只有登录的时候会根据id去查找device，读取频率不高，频率最高的是根据identifier读取device，所以其实只考虑identifier到device的缓存比较好。
4. 关于device表读写的性能优化比前三个要复杂很多，还得考虑数据量大了以后的分片操作，以及缓存根据业务场景的策略设计，所以不建议放在一个版本做，可以先做一个优化前三个表的版本合入后先验证。device的优化放到下一个版本。

**Comment by ruizeng** [comment]
@g4zhuj 已经修改了registry，取消了根据key直接从db读取device的逻辑。

**Comment by g4zhuj** [comment]
1.value部分内部使用interface{}对应不同的结构体，这里是否需要在cache包中提供每个表的Get及Set操作，如果不提供每个表的操作的话，这里将会只提供统一的Get及Set,Value部分类型为interface{},外部需要进行类型断言，这里是否妥当？

**Comment by ruizeng** [comment]
我认为无需在cache包中提供每个表的Get和Set，这样通用性太差。由上层使用者来做类型断言。

另外可以将cache生命为接口，定义Get，Set等通用方法，除了现在的MemoryCache，后续可以根据需求实现RedisCache，FileChache等实现。

**Comment by g4zhuj** [comment]
锐哥：
第一个版本完成了，实现了LRU算法置换内存，你先看一下代码，看有没有问题．(ps, 提交日志写成中文了，下次改正．)

**Comment by ruizeng** [comment]
神速。请直接从master合入最近的更新，给我发push request我来审核。

**Comment by g4zhuj** [comment]
master下push出现一下错误

remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected
To https://github.com/PandoCloud/pando-cloud.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: 无法推送一些引用到 'https://github.com/PandoCloud/pando-cloud.git'

**Comment by g4zhuj** [comment]
锐哥:
我看SaveVendor＼SaveProduct＼SaveApplication这几个接口里面通过orm的save接口实现了无记录插入，有记录更新．save在执行插入时会将插入前没有ID的值插入后附上ID值取出返回？另外加入缓存后需要显式的知道是插入还是更新，插入不操作缓存，更新要删除缓存中旧数据．这里的数据库操作可能需要先查询一下是否存在记录．

**Comment by ruizeng** [comment]
@g4zhuj save在没有提供id的时候会更新，提供id后就会保存并返回新值。使用的是[gorm](https://github.com/jinzhu/gorm)这个ORM库。

实际上我这里的`SaveVendor` `SaveProduct` `SaveApplication`是新建vendor而不是更新（更新是不一定需要更新key的）。所以这里的save及其注释是有一定的歧义。建议增加`UpdateVendor` `UpdateProduct` `UpdateApplication`三个接口，根据ID更新配置，根据传入的ID查询对应的记录并修改字段后Save，按照你刚才说的逻辑区分对待缓存更新，参考[这里](https://github.com/jinzhu/gorm#update)。
示例：

``` go
err := db.First(vendor, id).Error // id为RPC接口传入的id值
if err != nil {
  ...
}
db.Model(vendor).Updates(Vendor{VendorName: "hello", VendorDescription: "world"}) // vendor为传入的需要更新字段的结构体
```

另外，内存缓存的情况只适用于单实例部署`registry`服务，如果是多实例部署，可能还是需要共享内存的缓存如redis来实现缓存接口，这里后续注意保留扩展性。

**Comment by ruizeng** [comment]
@g4zhuj 修改了`SaveVendor SaveProduct SaveApplication`的代码，增加了判断逻辑，如果ID没有初始化就创建否则更新，暂时没有增加`UpdateVendor UpdateProduct UpdateApplication`。你可以在这个基础上增加缓存逻辑。
